import bcrypt from 'bcryptjs';
import { 
  User, Profile, Address, Seller, Category, Brand, 
  Product, Coupon, Banner, Review, Order 
} from '../types/index.js';

// Pre-hashed passwords for 'Admin@123', 'Seller@123', 'Customer@123'
const ADMIN_HASH = bcrypt.hashSync('Admin@123', 10);
const SELLER_HASH = bcrypt.hashSync('Seller@123', 10);
const CUSTOMER_HASH = bcrypt.hashSync('Customer@123', 10);

export const seedUsers: User[] = [
  {
    id: 'usr_admin_001',
    email: 'admin@prajnacart.com',
    passwordHash: ADMIN_HASH,
    phone: '+91 98765 43210',
    role: 'admin',
    isActive: true,
    isEmailVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'usr_seller_001',
    email: 'seller@prajnacart.com',
    passwordHash: SELLER_HASH,
    phone: '+91 91234 56789',
    role: 'seller',
    isActive: true,
    isEmailVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-02T00:00:00Z',
    updatedAt: '2026-01-02T00:00:00Z',
  },
  {
    id: 'usr_seller_002',
    email: 'techstore@prajnacart.com',
    passwordHash: SELLER_HASH,
    phone: '+91 98989 89898',
    role: 'seller',
    isActive: true,
    isEmailVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-03T00:00:00Z',
    updatedAt: '2026-01-03T00:00:00Z',
  },
  {
    id: 'usr_customer_001',
    email: 'customer@prajnacart.com',
    passwordHash: CUSTOMER_HASH,
    phone: '+91 98111 22233',
    role: 'customer',
    isActive: true,
    isEmailVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-01-05T00:00:00Z',
  }
];

export const seedProfiles: Profile[] = [
  {
    id: 'prof_001',
    userId: 'usr_admin_001',
    firstName: 'Prajnacart',
    lastName: 'Admin',
    gender: 'Other',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prof_002',
    userId: 'usr_seller_001',
    firstName: 'Apex',
    lastName: 'Retailers',
    gender: 'Male',
    createdAt: '2026-01-02T00:00:00Z',
    updatedAt: '2026-01-02T00:00:00Z',
  },
  {
    id: 'prof_003',
    userId: 'usr_customer_001',
    firstName: 'Rahul',
    lastName: 'Sharma',
    gender: 'Male',
    dateOfBirth: '1995-08-15',
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-01-05T00:00:00Z',
  }
];

export const seedSellers: Seller[] = [
  {
    id: 'seller_apex_01',
    userId: 'usr_seller_001',
    storeName: 'Apex Electronics & Lifestyle',
    storeSlug: 'apex-electronics',
    businessEmail: 'seller@prajnacart.com',
    businessPhone: '+91 91234 56789',
    gstin: '29ABCDE1234F1Z5',
    pan: 'ABCDE1234F',
    bankAccountName: 'Apex Retailers Private Limited',
    bankAccountNumber: '987654321098',
    bankIfsc: 'HDFC0001234',
    bankName: 'HDFC Bank',
    status: 'approved',
    rating: 4.8,
    ratingCount: 1420,
    commissionRate: 8.0,
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=120&auto=format&fit=crop&q=80',
    description: 'Authorized retailer for top global brands. 100% authentic products with fast dispatch and genuine warranties.',
    createdAt: '2026-01-02T00:00:00Z',
    updatedAt: '2026-01-02T00:00:00Z',
  },
  {
    id: 'seller_prime_02',
    userId: 'usr_seller_002',
    storeName: 'PrimeTech SuperStore',
    storeSlug: 'primetech-store',
    businessEmail: 'techstore@prajnacart.com',
    businessPhone: '+91 98989 89898',
    gstin: '07AAECP1234Q1Z8',
    pan: 'AAECP1234Q',
    bankAccountName: 'PrimeTech Digital Pvt Ltd',
    bankAccountNumber: '112233445566',
    bankIfsc: 'ICIC0000456',
    bankName: 'ICICI Bank',
    status: 'approved',
    rating: 4.6,
    ratingCount: 890,
    commissionRate: 8.0,
    logoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=120&auto=format&fit=crop&q=80',
    description: 'Premier gaming gear, computers, smart wearables and mobile accessories store.',
    createdAt: '2026-01-03T00:00:00Z',
    updatedAt: '2026-01-03T00:00:00Z',
  }
];

export const seedAddresses: Address[] = [
  {
    id: 'addr_001',
    userId: 'usr_customer_001',
    fullName: 'Rahul Sharma',
    phone: '9811122233',
    alternatePhone: '9876543211',
    addressLine1: 'Flat 402, Sunshine Heights, 12th Main Road',
    addressLine2: 'Indiranagar 2nd Stage',
    landmark: 'Near Indiranagar Metro Station',
    city: 'Bengaluru',
    state: 'Karnataka',
    postalCode: '560038',
    country: 'India',
    addressType: 'home',
    isDefault: true,
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'addr_002',
    userId: 'usr_customer_001',
    fullName: 'Rahul Sharma (Office)',
    phone: '9811122233',
    addressLine1: 'Tower B, 6th Floor, Global Tech Park',
    addressLine2: 'Outer Ring Road, Bellandur',
    landmark: 'Opposite EcoSpace',
    city: 'Bengaluru',
    state: 'Karnataka',
    postalCode: '560103',
    country: 'India',
    addressType: 'work',
    isDefault: false,
    createdAt: '2026-01-06T00:00:00Z',
    updatedAt: '2026-01-06T00:00:00Z',
  }
];

export const seedCategories: Category[] = [
  {
    id: 'cat_mobiles',
    name: 'Mobiles & Tablets',
    slug: 'mobiles',
    description: 'Smartphones, Tablets, Smartwatches & Accessories',
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=300&auto=format&fit=crop&q=80',
    iconName: 'Smartphone',
    displayOrder: 1,
    isActive: true,
    subcategories: [
      { id: 'sub_smartphones', categoryId: 'cat_mobiles', name: 'Smartphones', slug: 'smartphones', displayOrder: 1, isActive: true },
      { id: 'sub_tablets', categoryId: 'cat_mobiles', name: 'Tablets', slug: 'tablets', displayOrder: 2, isActive: true },
      { id: 'sub_wearables', categoryId: 'cat_mobiles', name: 'Smart Watches', slug: 'smart-watches', displayOrder: 3, isActive: true },
      { id: 'sub_mobile_acc', categoryId: 'cat_mobiles', name: 'Mobile Accessories', slug: 'accessories', displayOrder: 4, isActive: true },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_electronics',
    name: 'Electronics & Gadgets',
    slug: 'electronics',
    description: 'Laptops, Headphones, Cameras & Audio',
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=300&auto=format&fit=crop&q=80',
    iconName: 'Laptop',
    displayOrder: 2,
    isActive: true,
    subcategories: [
      { id: 'sub_laptops', categoryId: 'cat_electronics', name: 'Laptops', slug: 'laptops', displayOrder: 1, isActive: true },
      { id: 'sub_audio', categoryId: 'cat_electronics', name: 'Headphones & Speakers', slug: 'audio', displayOrder: 2, isActive: true },
      { id: 'sub_gaming', categoryId: 'cat_electronics', name: 'Gaming Consoles & Gear', slug: 'gaming', displayOrder: 3, isActive: true },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_fashion_men',
    name: 'Men Fashion',
    slug: 'men-fashion',
    description: 'Clothing, Footwear, Watches & Accessories for Men',
    imageUrl: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=300&auto=format&fit=crop&q=80',
    iconName: 'Shirt',
    displayOrder: 3,
    isActive: true,
    subcategories: [
      { id: 'sub_men_shirts', categoryId: 'cat_fashion_men', name: 'Shirts & T-Shirts', slug: 'shirts-tshirts', displayOrder: 1, isActive: true },
      { id: 'sub_men_shoes', categoryId: 'cat_fashion_men', name: 'Sneakers & Shoes', slug: 'shoes', displayOrder: 2, isActive: true },
      { id: 'sub_men_jackets', categoryId: 'cat_fashion_men', name: 'Jackets & Blazers', slug: 'jackets', displayOrder: 3, isActive: true },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_fashion_women',
    name: 'Women Fashion',
    slug: 'women-fashion',
    description: 'Ethnic Wear, Western Wear, Handbags & Footwear',
    imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=300&auto=format&fit=crop&q=80',
    iconName: 'Sparkles',
    displayOrder: 4,
    isActive: true,
    subcategories: [
      { id: 'sub_women_ethnic', categoryId: 'cat_fashion_women', name: 'Ethnic Wear & Sarees', slug: 'ethnic-wear', displayOrder: 1, isActive: true },
      { id: 'sub_women_dresses', categoryId: 'cat_fashion_women', name: 'Dresses & Tops', slug: 'dresses', displayOrder: 2, isActive: true },
      { id: 'sub_women_bags', categoryId: 'cat_fashion_women', name: 'Handbags & Clutches', slug: 'handbags', displayOrder: 3, isActive: true },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_home_kitchen',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    description: 'Cookware, Kitchen Appliances, Furnishing & Decor',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=300&auto=format&fit=crop&q=80',
    iconName: 'Home',
    displayOrder: 5,
    isActive: true,
    subcategories: [
      { id: 'sub_appliances', categoryId: 'cat_home_kitchen', name: 'Kitchen Appliances', slug: 'appliances', displayOrder: 1, isActive: true },
      { id: 'sub_furnishing', categoryId: 'cat_home_kitchen', name: 'Home Decor & Bedsheets', slug: 'decor', displayOrder: 2, isActive: true },
      { id: 'sub_cookware', categoryId: 'cat_home_kitchen', name: 'Cookware & Dinnerware', slug: 'cookware', displayOrder: 3, isActive: true },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_appliances',
    name: 'TVs & Appliances',
    slug: 'appliances',
    description: 'Smart TVs, Air Conditioners, Refrigerators & Washing Machines',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=300&auto=format&fit=crop&q=80',
    iconName: 'Tv',
    displayOrder: 6,
    isActive: true,
    subcategories: [
      { id: 'sub_tvs', categoryId: 'cat_appliances', name: 'Smart TVs', slug: 'smart-tvs', displayOrder: 1, isActive: true },
      { id: 'sub_refrigerators', categoryId: 'cat_appliances', name: 'Refrigerators', slug: 'refrigerators', displayOrder: 2, isActive: true },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_beauty',
    name: 'Beauty & Grooming',
    slug: 'beauty',
    description: 'Skincare, Haircare, Fragrances & Makeup',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=300&auto=format&fit=crop&q=80',
    iconName: 'HeartHandshake',
    displayOrder: 7,
    isActive: true,
    subcategories: [
      { id: 'sub_skincare', categoryId: 'cat_beauty', name: 'Skincare', slug: 'skincare', displayOrder: 1, isActive: true },
      { id: 'sub_perfumes', categoryId: 'cat_beauty', name: 'Fragrances & Perfumes', slug: 'fragrances', displayOrder: 2, isActive: true },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_grocery',
    name: 'Grocery & Essentials',
    slug: 'grocery',
    description: 'Daily staples, Snacks, Beverages and Organic Food',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=300&auto=format&fit=crop&q=80',
    iconName: 'ShoppingBag',
    displayOrder: 8,
    isActive: true,
    subcategories: [
      { id: 'sub_staples', categoryId: 'cat_grocery', name: 'Cooking Staples', slug: 'staples', displayOrder: 1, isActive: true },
      { id: 'sub_coffee_tea', categoryId: 'cat_grocery', name: 'Tea & Coffee', slug: 'beverages', displayOrder: 2, isActive: true },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_sports',
    name: 'Sports & Fitness',
    slug: 'sports',
    description: 'Gym Equipment, Fitness Accessories & Activewear',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=300&auto=format&fit=crop&q=80',
    iconName: 'Dumbbell',
    displayOrder: 9,
    isActive: true,
    subcategories: [
      { id: 'sub_fitness', categoryId: 'cat_sports', name: 'Gym & Fitness', slug: 'fitness', displayOrder: 1, isActive: true },
      { id: 'sub_outdoor', categoryId: 'cat_sports', name: 'Outdoor Gear', slug: 'outdoor', displayOrder: 2, isActive: true },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_books',
    name: 'Books & Stationery',
    slug: 'books',
    description: 'Best-selling fiction, Self-help, Competitive exam books & Pens',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=300&auto=format&fit=crop&q=80',
    iconName: 'BookOpen',
    displayOrder: 10,
    isActive: true,
    subcategories: [
      { id: 'sub_fiction', categoryId: 'cat_books', name: 'Fiction & Non-Fiction', slug: 'books-all', displayOrder: 1, isActive: true },
      { id: 'sub_stationery', categoryId: 'cat_books', name: 'Premium Stationery', slug: 'stationery', displayOrder: 2, isActive: true },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  }
];

export const seedBrands: Brand[] = [
  { id: 'b_apple', name: 'Apple', slug: 'apple', isFeatured: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'b_samsung', name: 'Samsung', slug: 'samsung', isFeatured: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'b_sony', name: 'Sony', slug: 'sony', isFeatured: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'b_nike', name: 'Nike', slug: 'nike', isFeatured: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'b_adidas', name: 'Adidas', slug: 'adidas', isFeatured: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'b_asus', name: 'ASUS', slug: 'asus', isFeatured: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'b_boat', name: 'boAt', slug: 'boat', isFeatured: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'b_oneplus', name: 'OnePlus', slug: 'oneplus', isFeatured: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'b_philips', name: 'Philips', slug: 'philips', isFeatured: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'b_puma', name: 'Puma', slug: 'puma', isFeatured: true, createdAt: '2026-01-01T00:00:00Z' }
];

export const seedBanners: Banner[] = [
  {
    id: 'ban_001',
    title: 'Grand Super Electronic Festival',
    subtitle: 'Up to 50% OFF on Flagship Smartphones, Laptops & Premium Audio',
    imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1440&auto=format&fit=crop&q=80',
    mobileImageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&auto=format&fit=crop&q=80',
    ctaText: 'Explore Tech Deals',
    ctaLink: '/category/electronics',
    badgeText: 'LIMITED TIME DEAL',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'ban_002',
    title: 'Festive Fashion Carnival',
    subtitle: 'Min 60% OFF on Men, Women & Kids Trendiest Styles',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1440&auto=format&fit=crop&q=80',
    mobileImageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&auto=format&fit=crop&q=80',
    ctaText: 'Shop Fashion',
    ctaLink: '/category/men-fashion',
    badgeText: 'TOP STYLES',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'ban_003',
    title: 'Upgrade Your Living Space',
    subtitle: 'Smart Kitchen Appliances & Premium Furnishings starting @ ₹499',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1440&auto=format&fit=crop&q=80',
    mobileImageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    ctaText: 'Upgrade Home',
    ctaLink: '/category/home-kitchen',
    badgeText: 'BESTSELLERS',
    displayOrder: 3,
    isActive: true,
  }
];

export const seedCoupons: Coupon[] = [
  {
    id: 'c_welcome100',
    code: 'WELCOME100',
    description: 'Flat ₹100 instant discount on your first marketplace order',
    discountType: 'flat',
    discountValue: 100,
    minOrderValue: 499,
    usageLimit: 10000,
    usedCount: 142,
    perUserLimit: 1,
    isActive: true,
  },
  {
    id: 'c_festive20',
    code: 'FESTIVE20',
    description: '20% OFF on Electronics & Fashion (Max ₹1,500 savings)',
    discountType: 'percentage',
    discountValue: 20,
    minOrderValue: 1499,
    maxDiscountValue: 1500,
    usageLimit: 5000,
    usedCount: 680,
    perUserLimit: 2,
    isActive: true,
  },
  {
    id: 'c_super500',
    code: 'SUPER500',
    description: 'Flat ₹500 discount on orders above ₹4,999',
    discountType: 'flat',
    discountValue: 500,
    minOrderValue: 4999,
    usageLimit: 2000,
    usedCount: 89,
    perUserLimit: 1,
    isActive: true,
  },
  {
    id: 'c_freeship',
    code: 'FREESHIP',
    description: 'Free Express Shipping on any order value',
    discountType: 'flat',
    discountValue: 40,
    minOrderValue: 0,
    usageLimit: 20000,
    usedCount: 1200,
    perUserLimit: 5,
    isActive: true,
  }
];

export const seedProducts: Product[] = [
  // 1. Apple iPhone 15 Pro Max
  {
    id: 'prod_ip15promax',
    title: 'Apple iPhone 15 Pro Max (Natural Titanium, 256 GB)',
    slug: 'apple-iphone-15-pro-max-256gb',
    sku: 'AAPL-IP15PM-256-NAT',
    shortDescription: '6.7-inch Super Retina XDR display, A17 Pro Chip, 48MP Main Camera, Grade 5 Titanium design.',
    description: 'iPhone 15 Pro Max is forged in aerospace-grade titanium that’s strong yet light to deliver Apple’s lightest Pro models ever. The design also features contoured edges and a customizable Action button. Powerful camera upgrades enable the equivalent of seven pro lenses with incredible image quality, including a 48MP Main camera system, next-generation portraits, and an all-new 5x Telephoto camera.',
    categoryId: 'cat_mobiles',
    categoryName: 'Mobiles & Tablets',
    categorySlug: 'mobiles',
    subcategoryId: 'sub_smartphones',
    subcategoryName: 'Smartphones',
    brandId: 'b_apple',
    brandName: 'Apple',
    sellerId: 'seller_apex_01',
    sellerStoreName: 'Apex Electronics & Lifestyle',
    mrp: 159900,
    price: 139900,
    discountPercent: 12,
    taxPercent: 18,
    stockQuantity: 45,
    thumbnailUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
    ],
    variants: [
      { id: 'var_ip15_nat_256', productId: 'prod_ip15promax', sku: 'AAPL-IP15PM-256-NAT', variantName: 'Natural Titanium / 256GB', color: 'Natural Titanium', colorCode: '#B4AEA3', storage: '256GB', mrp: 159900, price: 139900, stockQuantity: 20 },
      { id: 'var_ip15_blk_256', productId: 'prod_ip15promax', sku: 'AAPL-IP15PM-256-BLK', variantName: 'Black Titanium / 256GB', color: 'Black Titanium', colorCode: '#2B2B2B', storage: '256GB', mrp: 159900, price: 139900, stockQuantity: 15 },
      { id: 'var_ip15_nat_512', productId: 'prod_ip15promax', sku: 'AAPL-IP15PM-512-NAT', variantName: 'Natural Titanium / 512GB', color: 'Natural Titanium', colorCode: '#B4AEA3', storage: '512GB', mrp: 179900, price: 159900, stockQuantity: 10 },
    ],
    rating: 4.8,
    ratingCount: 3840,
    reviewCount: 920,
    isActive: true,
    isFeatured: true,
    isDealOfTheDay: true,
    approvalStatus: 'approved',
    warrantyInfo: '1 Year Apple International Hardware Warranty',
    returnPolicy: '7 Days Replacement Policy for Hardware Defects',
    deliveryInfo: 'Express Delivery by Tomorrow 8 PM',
    specifications: [
      { group: 'General', items: [{ name: 'Model Name', value: 'iPhone 15 Pro Max' }, { name: 'Color', value: 'Natural Titanium' }, { name: 'SIM Type', value: 'Dual SIM (eSIM + Nano)' }] },
      { group: 'Display Features', items: [{ name: 'Display Size', value: '6.7 inch' }, { name: 'Resolution', value: '2796 x 1290 Pixels' }, { name: 'Display Type', value: 'Super Retina XDR OLED ProMotion 120Hz' }] },
      { group: 'Processor & Memory', items: [{ name: 'Processor', value: 'A17 Pro Chip 6-core CPU' }, { name: 'Internal Storage', value: '256 GB' }] },
      { group: 'Camera Features', items: [{ name: 'Primary Camera', value: '48MP + 12MP + 12MP' }, { name: 'Front Camera', value: '12MP TrueDepth' }] }
    ],
    tags: ['apple', 'iphone', '5g', 'smartphone', 'flagship', 'pro max'],
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-01-05T00:00:00Z',
  },

  // 2. Samsung Galaxy S24 Ultra
  {
    id: 'prod_s24ultra',
    title: 'Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB RAM, 256GB Storage)',
    slug: 'samsung-galaxy-s24-ultra-5g',
    sku: 'SMSNG-S24U-256-GRY',
    shortDescription: 'Galaxy AI is here. 200MP Quad Telephoto Camera, Snapdragon 8 Gen 3 for Galaxy, S Pen included.',
    description: 'Welcome to the era of mobile AI. With Galaxy S24 Ultra in your hands, you can unleash whole new levels of creativity, productivity and possibility — starting with the most important device in your life. Your phone.',
    categoryId: 'cat_mobiles',
    categoryName: 'Mobiles & Tablets',
    categorySlug: 'mobiles',
    subcategoryId: 'sub_smartphones',
    subcategoryName: 'Smartphones',
    brandId: 'b_samsung',
    brandName: 'Samsung',
    sellerId: 'seller_apex_01',
    sellerStoreName: 'Apex Electronics & Lifestyle',
    mrp: 134999,
    price: 119999,
    discountPercent: 11,
    taxPercent: 18,
    stockQuantity: 38,
    thumbnailUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80',
    ],
    variants: [
      { id: 'var_s24_gry_256', productId: 'prod_s24ultra', sku: 'SMSNG-S24U-256-GRY', variantName: 'Titanium Gray / 12GB / 256GB', color: 'Titanium Gray', colorCode: '#666666', ram: '12GB', storage: '256GB', mrp: 134999, price: 119999, stockQuantity: 20 },
      { id: 'var_s24_blk_512', productId: 'prod_s24ultra', sku: 'SMSNG-S24U-512-BLK', variantName: 'Titanium Black / 12GB / 512GB', color: 'Titanium Black', colorCode: '#1A1A1A', ram: '12GB', storage: '512GB', mrp: 149999, price: 129999, stockQuantity: 18 },
    ],
    rating: 4.7,
    ratingCount: 2980,
    reviewCount: 710,
    isActive: true,
    isFeatured: true,
    isDealOfTheDay: true,
    approvalStatus: 'approved',
    warrantyInfo: '1 Year Manufacturer Warranty for Device and 6 Months for In-Box Accessories',
    returnPolicy: '7 Days Replacement Policy',
    deliveryInfo: 'Free Delivery within 2 Days',
    specifications: [
      { group: 'General', items: [{ name: 'Model Name', value: 'Galaxy S24 Ultra 5G' }, { name: 'Processor', value: 'Snapdragon 8 Gen 3 Mobile Platform' }] },
      { group: 'Camera', items: [{ name: 'Rear Camera', value: '200MP + 50MP + 12MP + 10MP' }, { name: 'Front Camera', value: '12MP' }] },
      { group: 'Battery', items: [{ name: 'Battery Capacity', value: '5000 mAh Fast Charging' }] }
    ],
    tags: ['samsung', 'galaxy', 's24 ultra', 'ai', '5g', 'flagship'],
    createdAt: '2026-01-06T00:00:00Z',
    updatedAt: '2026-01-06T00:00:00Z',
  },

  // 3. Sony WH-1000XM5 Wireless Headphones
  {
    id: 'prod_sony_xm5',
    title: 'Sony WH-1000XM5 Industry Leading Wireless Noise Cancelling Headphones',
    slug: 'sony-wh-1000xm5-wireless-headphones',
    sku: 'SNY-WH1000XM5-BLK',
    shortDescription: 'Magnificent Sound Engineered to Perfection with 2 Processors & 8 Microphones, 30hr Battery Life.',
    description: 'The WH-1000XM5 headphones rewrite the rules for distraction-free listening. Two processors control 8 microphones for unprecedented noise cancellation and exceptional call quality.',
    categoryId: 'cat_electronics',
    categoryName: 'Electronics & Gadgets',
    categorySlug: 'electronics',
    subcategoryId: 'sub_audio',
    subcategoryName: 'Headphones & Speakers',
    brandId: 'b_sony',
    brandName: 'Sony',
    sellerId: 'seller_prime_02',
    sellerStoreName: 'PrimeTech SuperStore',
    mrp: 34990,
    price: 26990,
    discountPercent: 23,
    taxPercent: 18,
    stockQuantity: 60,
    thumbnailUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    ],
    variants: [
      { id: 'var_xm5_blk', productId: 'prod_sony_xm5', sku: 'SNY-WH1000XM5-BLK', variantName: 'Midnight Black', color: 'Black', colorCode: '#111111', mrp: 34990, price: 26990, stockQuantity: 35 },
      { id: 'var_xm5_slv', productId: 'prod_sony_xm5', sku: 'SNY-WH1000XM5-SLV', variantName: 'Platinum Silver', color: 'Silver', colorCode: '#E5E5E5', mrp: 34990, price: 26990, stockQuantity: 25 },
    ],
    rating: 4.9,
    ratingCount: 1840,
    reviewCount: 430,
    isActive: true,
    isFeatured: true,
    isDealOfTheDay: false,
    approvalStatus: 'approved',
    warrantyInfo: '1 Year Domestic Brand Warranty',
    returnPolicy: '7 Days Replacement Policy',
    deliveryInfo: 'Free Delivery by Friday',
    specifications: [
      { group: 'Audio', items: [{ name: 'Driver Size', value: '30mm' }, { name: 'Frequency Response', value: '4Hz - 40,000Hz' }, { name: 'Noise Cancellation', value: 'Dual Processor Active ANC' }] },
      { group: 'Connectivity', items: [{ name: 'Bluetooth Version', value: '5.2 with LDAC & Multipoint' }, { name: 'Battery Life', value: 'Up to 30 Hours with ANC ON' }] }
    ],
    tags: ['sony', 'headphones', 'anc', 'wireless', 'music', 'audiophile'],
    createdAt: '2026-01-07T00:00:00Z',
    updatedAt: '2026-01-07T00:00:00Z',
  },

  // 4. ASUS ROG Zephyrus G16 Gaming Laptop
  {
    id: 'prod_asus_rog16',
    title: 'ASUS ROG Zephyrus G16 (2026) OLED 2.5K 240Hz, Intel Core Ultra 9, RTX 4080',
    slug: 'asus-rog-zephyrus-g16-gaming-laptop',
    sku: 'ASUS-ROG-G16-U9-4080',
    shortDescription: '16-inch 2.5K ROG Nebula OLED Display, 32GB LPDDR5X RAM, 1TB PCIe 4.0 SSD, CNC Aluminum Chassis.',
    description: 'Precision, power, and elegance unite in the all-new 2026 ROG Zephyrus G16. Powered by up to an Intel Core Ultra 9 processor and NVIDIA GeForce RTX 4080 Laptop GPU, this machine effortlessly crushes modern AAA games and creative workflows.',
    categoryId: 'cat_electronics',
    categoryName: 'Electronics & Gadgets',
    categorySlug: 'electronics',
    subcategoryId: 'sub_laptops',
    subcategoryName: 'Laptops',
    brandId: 'b_asus',
    brandName: 'ASUS',
    sellerId: 'seller_prime_02',
    sellerStoreName: 'PrimeTech SuperStore',
    mrp: 239990,
    price: 199990,
    discountPercent: 17,
    taxPercent: 18,
    stockQuantity: 15,
    thumbnailUrl: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80',
    ],
    variants: [
      { id: 'var_rog16_32_1tb', productId: 'prod_asus_rog16', sku: 'ASUS-ROG-G16-U9-4080', variantName: 'Eclipse Gray / 32GB RAM / 1TB SSD', color: 'Eclipse Gray', colorCode: '#3A3B3C', ram: '32GB', storage: '1TB SSD', mrp: 239990, price: 199990, stockQuantity: 15 },
    ],
    rating: 4.8,
    ratingCount: 520,
    reviewCount: 110,
    isActive: true,
    isFeatured: true,
    isDealOfTheDay: false,
    approvalStatus: 'approved',
    warrantyInfo: '2 Years Onsite Brand Warranty with 1 Year Accidental Damage Protection',
    returnPolicy: '7 Days Replacement Policy',
    deliveryInfo: 'Free Express Shipping',
    specifications: [
      { group: 'Processor & Graphics', items: [{ name: 'Processor', value: 'Intel Core Ultra 9 185H' }, { name: 'Graphics', value: 'NVIDIA GeForce RTX 4080 (12GB GDDR6)' }] },
      { group: 'Display', items: [{ name: 'Size & Panel', value: '16.0-inch 2.5K (2560 x 1600) ROG Nebula OLED 240Hz 0.2ms' }, { name: 'Color Gamut', value: '100% DCI-P3, G-SYNC Supported' }] }
    ],
    tags: ['asus', 'rog', 'laptop', 'gaming', 'oled', 'rtx 4080'],
    createdAt: '2026-01-08T00:00:00Z',
    updatedAt: '2026-01-08T00:00:00Z',
  },

  // 5. Nike Air Jordan 1 Retro High OG
  {
    id: 'prod_nike_aj1',
    title: 'Nike Air Jordan 1 Retro High OG Chicago Lost & Found',
    slug: 'nike-air-jordan-1-retro-high-og',
    sku: 'NIKE-AJ1-OG-CHI',
    shortDescription: 'Iconic high-top basketball sneaker in vintage leather Chicago colorway with encapsulated Air-Sole cushioning.',
    description: 'The Air Jordan 1 Retro High OG brings back the beloved silhouette in a vintage distressed aesthetic. Featuring genuine leather, a high-top collar, and timeless court heritage.',
    categoryId: 'cat_fashion_men',
    categoryName: 'Men Fashion',
    categorySlug: 'men-fashion',
    subcategoryId: 'sub_men_shoes',
    subcategoryName: 'Sneakers & Shoes',
    brandId: 'b_nike',
    brandName: 'Nike',
    sellerId: 'seller_apex_01',
    sellerStoreName: 'Apex Electronics & Lifestyle',
    mrp: 18995,
    price: 14995,
    discountPercent: 21,
    taxPercent: 12,
    stockQuantity: 50,
    thumbnailUrl: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
    ],
    variants: [
      { id: 'var_aj1_uk8', productId: 'prod_nike_aj1', sku: 'NIKE-AJ1-UK8', variantName: 'Varsity Red/White/Black - UK 8', size: 'UK 8', color: 'Varsity Red/Black', colorCode: '#B22222', mrp: 18995, price: 14995, stockQuantity: 15 },
      { id: 'var_aj1_uk9', productId: 'prod_nike_aj1', sku: 'NIKE-AJ1-UK9', variantName: 'Varsity Red/White/Black - UK 9', size: 'UK 9', color: 'Varsity Red/Black', colorCode: '#B22222', mrp: 18995, price: 14995, stockQuantity: 20 },
      { id: 'var_aj1_uk10', productId: 'prod_nike_aj1', sku: 'NIKE-AJ1-UK10', variantName: 'Varsity Red/White/Black - UK 10', size: 'UK 10', color: 'Varsity Red/Black', colorCode: '#B22222', mrp: 18995, price: 14995, stockQuantity: 15 },
    ],
    rating: 4.9,
    ratingCount: 1520,
    reviewCount: 380,
    isActive: true,
    isFeatured: true,
    isDealOfTheDay: false,
    approvalStatus: 'approved',
    warrantyInfo: '6 Months Brand Warranty against manufacturing defects',
    returnPolicy: '14 Days Free Return / Exchange',
    deliveryInfo: 'Free Delivery Available',
    specifications: [
      { group: 'Product Details', items: [{ name: 'Outer Material', value: '100% Genuine Leather' }, { name: 'Sole Material', value: 'Rubber Cupsole with Air Unit' }, { name: 'Closure', value: 'Lace-Up' }] }
    ],
    tags: ['nike', 'jordan', 'sneakers', 'streetwear', 'mens footwear'],
    createdAt: '2026-01-09T00:00:00Z',
    updatedAt: '2026-01-09T00:00:00Z',
  },

  // 6. Adidas Men Essentials Warm-Up 3-Stripes Track Jacket
  {
    id: 'prod_adidas_jacket',
    title: 'Adidas Men Essentials 3-Stripes Warm-Up Track Jacket',
    slug: 'adidas-men-essentials-3-stripes-jacket',
    sku: 'ADI-TRK-JKT-BLK',
    shortDescription: 'Classic tricot fabric sports jacket with full-zip front and signature 3-stripes along sleeves.',
    description: 'Zip up sport style in this iconic Adidas jacket. Built from soft recycled tricot with ribbed cuffs and hem to lock in warmth.',
    categoryId: 'cat_fashion_men',
    categoryName: 'Men Fashion',
    categorySlug: 'men-fashion',
    subcategoryId: 'sub_men_jackets',
    subcategoryName: 'Jackets & Blazers',
    brandId: 'b_adidas',
    brandName: 'Adidas',
    sellerId: 'seller_apex_01',
    sellerStoreName: 'Apex Electronics & Lifestyle',
    mrp: 3999,
    price: 2199,
    discountPercent: 45,
    taxPercent: 12,
    stockQuantity: 80,
    thumbnailUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&auto=format&fit=crop&q=80',
    ],
    variants: [
      { id: 'var_adi_m', productId: 'prod_adidas_jacket', sku: 'ADI-JKT-M', variantName: 'Black/White - M', size: 'M', color: 'Black', colorCode: '#000000', mrp: 3999, price: 2199, stockQuantity: 30 },
      { id: 'var_adi_l', productId: 'prod_adidas_jacket', sku: 'ADI-JKT-L', variantName: 'Black/White - L', size: 'L', color: 'Black', colorCode: '#000000', mrp: 3999, price: 2199, stockQuantity: 30 },
      { id: 'var_adi_xl', productId: 'prod_adidas_jacket', sku: 'ADI-JKT-XL', variantName: 'Black/White - XL', size: 'XL', color: 'Black', colorCode: '#000000', mrp: 3999, price: 2199, stockQuantity: 20 },
    ],
    rating: 4.6,
    ratingCount: 940,
    reviewCount: 180,
    isActive: true,
    isFeatured: false,
    isDealOfTheDay: true,
    approvalStatus: 'approved',
    warrantyInfo: '3 Months Brand Warranty',
    returnPolicy: '14 Days Free Return',
    deliveryInfo: 'Delivered in 2-3 Business Days',
    specifications: [
      { group: 'Details', items: [{ name: 'Material', value: '100% Recycled Polyester Tricot' }, { name: 'Fit', value: 'Regular Fit' }, { name: 'Pattern', value: 'Solid with Side Stripes' }] }
    ],
    tags: ['adidas', 'jacket', 'mens fashion', 'sportswear'],
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },

  // 7. Pure Silk Banarasi Saree with Zari Work
  {
    id: 'prod_banarasi_saree',
    title: 'Varkha Luxury Woven Pure Kanjeevaram Banarasi Silk Saree with Blouse Piece',
    slug: 'pure-banarasi-silk-saree-zari-work',
    slugBackup: 'banarasi-silk-saree',
    sku: 'VRK-BANARASI-ROYALRED',
    shortDescription: 'Intricate golden zari jaal pattern on pure mulberry silk with rich contrast pallu.',
    description: 'Drape yourself in royal Indian elegance with this handcrafted Banarasi silk saree. Adorned with exquisite gold zari floral bootas, a heavy woven border, and comes with an unstitched matching blouse piece.',
    categoryId: 'cat_fashion_women',
    categoryName: 'Women Fashion',
    categorySlug: 'women-fashion',
    subcategoryId: 'sub_women_ethnic',
    subcategoryName: 'Ethnic Wear & Sarees',
    brandName: 'Varkha Heritage',
    sellerId: 'seller_apex_01',
    sellerStoreName: 'Apex Electronics & Lifestyle',
    mrp: 9999,
    price: 3499,
    discountPercent: 65,
    taxPercent: 5,
    stockQuantity: 40,
    thumbnailUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
    ],
    variants: [
      { id: 'var_saree_red', productId: 'prod_banarasi_saree', sku: 'VRK-SAR-RED', variantName: 'Royal Crimson Red', color: 'Crimson Red', colorCode: '#990000', mrp: 9999, price: 3499, stockQuantity: 20 },
      { id: 'var_saree_grn', productId: 'prod_banarasi_saree', sku: 'VRK-SAR-GRN', variantName: 'Emerald Peacock Green', color: 'Emerald Green', colorCode: '#005533', mrp: 9999, price: 3499, stockQuantity: 20 },
    ],
    rating: 4.7,
    ratingCount: 1120,
    reviewCount: 310,
    isActive: true,
    isFeatured: true,
    isDealOfTheDay: true,
    approvalStatus: 'approved',
    warrantyInfo: 'Silk Mark Certified Pure Silk Guarantee',
    returnPolicy: '7 Days Returnable',
    deliveryInfo: 'Free Express Shipping across India',
    specifications: [
      { group: 'Saree Details', items: [{ name: 'Saree Fabric', value: 'Pure Katan Silk' }, { name: 'Length', value: '5.5 m saree + 0.8 m blouse' }, { name: 'Weave Type', value: 'Banarasi Zari Handloom Weave' }] }
    ],
    tags: ['saree', 'silk', 'ethnic wear', 'wedding', 'banarasi'],
    createdAt: '2026-01-11T00:00:00Z',
    updatedAt: '2026-01-11T00:00:00Z',
  },

  // 8. Philips Digital Air Fryer HD9252
  {
    id: 'prod_philips_airfryer',
    title: 'Philips Digital Air Fryer HD9252/90 with Rapid Air Technology (4.1 Litre)',
    slug: 'philips-digital-air-fryer-4-1l',
    sku: 'PHL-AF-HD9252-BLK',
    shortDescription: 'Fry with up to 90% less fat. 7 Preset touch screen programs with Keep Warm function.',
    description: 'Philips brings the World’s No.1 Airfryer to everyone’s home. Enjoy healthy food that’s crispy on the outside and tender on the inside, thanks to Rapid Air Technology. Download the NutriU app to discover hundreds of tasty recipes every day.',
    categoryId: 'cat_home_kitchen',
    categoryName: 'Home & Kitchen',
    categorySlug: 'home-kitchen',
    subcategoryId: 'sub_appliances',
    subcategoryName: 'Kitchen Appliances',
    brandId: 'b_philips',
    brandName: 'Philips',
    sellerId: 'seller_prime_02',
    sellerStoreName: 'PrimeTech SuperStore',
    mrp: 11995,
    price: 6999,
    discountPercent: 41,
    taxPercent: 18,
    stockQuantity: 55,
    thumbnailUrl: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.6,
    ratingCount: 3400,
    reviewCount: 780,
    isActive: true,
    isFeatured: true,
    isDealOfTheDay: false,
    approvalStatus: 'approved',
    warrantyInfo: '2 Years Comprehensive Philips Worldwide Warranty',
    returnPolicy: '10 Days Replacement for transit defects',
    deliveryInfo: 'Get it by Tomorrow with Express Dispatch',
    specifications: [
      { group: 'Capacity & Power', items: [{ name: 'Capacity', value: '4.1 Liters' }, { name: 'Power Consumption', value: '1400 Watts' }, { name: 'Temperature Range', value: '60°C - 200°C' }] },
      { group: 'Features', items: [{ name: 'Controls', value: 'Digital LED Touch Screen' }, { name: 'Auto Shut-Off', value: 'Yes' }] }
    ],
    tags: ['airfryer', 'philips', 'kitchen', 'healthy cooking', 'appliances'],
    createdAt: '2026-01-12T00:00:00Z',
    updatedAt: '2026-01-12T00:00:00Z',
  },

  // 9. Sony Bravia 55-inch 4K Ultra HD Smart Google TV
  {
    id: 'prod_sony_tv55',
    title: 'Sony Bravia 139 cm (55 inches) 4K Ultra HD Smart LED Google TV KD-55X74L',
    slug: 'sony-bravia-55-inch-4k-google-tv',
    sku: 'SNY-TV-55X74L-BLK',
    shortDescription: 'X1 4K Processor, Live Color, Dolby Audio, Apple AirPlay, Voice Search Remote.',
    description: 'Experience thrilling movies and games in 4K HDR with vibrant colors and rich details powered by Sony’s 4K Processor X1 and 4K X-Reality PRO picture engine.',
    categoryId: 'cat_appliances',
    categoryName: 'TVs & Appliances',
    categorySlug: 'appliances',
    subcategoryId: 'sub_tvs',
    subcategoryName: 'Smart TVs',
    brandId: 'b_sony',
    brandName: 'Sony',
    sellerId: 'seller_prime_02',
    sellerStoreName: 'PrimeTech SuperStore',
    mrp: 99900,
    price: 57990,
    discountPercent: 42,
    taxPercent: 18,
    stockQuantity: 22,
    thumbnailUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    ratingCount: 4210,
    reviewCount: 950,
    isActive: true,
    isFeatured: true,
    isDealOfTheDay: true,
    approvalStatus: 'approved',
    warrantyInfo: '3 Years Comprehensive Brand Warranty (1 Year Full + 2 Years on Panel)',
    returnPolicy: '10 Days Replacement Policy for Technical Defects',
    deliveryInfo: 'Free Delivery & Free Wall Mount Installation within 48 Hours',
    specifications: [
      { group: 'Display', items: [{ name: 'Resolution', value: '4K Ultra HD (3840 x 2160)' }, { name: 'Refresh Rate', value: '60 Hz Motionflow XR 100' }] },
      { group: 'Smart TV Features', items: [{ name: 'OS', value: 'Google TV with Play Store, Netflix, Prime' }, { name: 'Audio Output', value: '20 Watts Open Baffle Speaker with Dolby Audio' }] }
    ],
    tags: ['sony', 'tv', '4k', 'smart tv', 'google tv', 'bravia'],
    createdAt: '2026-01-13T00:00:00Z',
    updatedAt: '2026-01-13T00:00:00Z',
  },

  // 10. boAt Airdopes 141 ANC True Wireless Earbuds
  {
    id: 'prod_boat_air141',
    title: 'boAt Airdopes 141 ANC with 32dB Active Noise Cancellation, 42H Playtime',
    slug: 'boat-airdopes-141-anc-true-wireless-earbuds',
    sku: 'BOAT-AD-141-ANC-GUN',
    shortDescription: 'Up to 32dB ANC, ASAP Charge (10 mins = 150 mins playback), ENx Quad Mics for crystal clear calls.',
    description: 'Drown out unwanted noise and immerse yourself in pure Nirvana sound with the boAt Airdopes 141 ANC. Engineered with low-latency BEAST Mode for seamless mobile gaming.',
    categoryId: 'cat_electronics',
    categoryName: 'Electronics & Gadgets',
    categorySlug: 'electronics',
    subcategoryId: 'sub_audio',
    subcategoryName: 'Headphones & Speakers',
    brandId: 'b_boat',
    brandName: 'boAt',
    sellerId: 'seller_apex_01',
    sellerStoreName: 'Apex Electronics & Lifestyle',
    mrp: 5990,
    price: 1499,
    discountPercent: 75,
    taxPercent: 18,
    stockQuantity: 120,
    thumbnailUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    ],
    variants: [
      { id: 'var_boat_gun', productId: 'prod_boat_air141', sku: 'BOAT-141-GUN', variantName: 'Gunmetal Black', color: 'Gunmetal Black', colorCode: '#222222', mrp: 5990, price: 1499, stockQuantity: 60 },
      { id: 'var_boat_wht', productId: 'prod_boat_air141', sku: 'BOAT-141-WHT', variantName: 'Glacier White', color: 'White', colorCode: '#F5F5F5', mrp: 5990, price: 1499, stockQuantity: 60 },
    ],
    rating: 4.4,
    ratingCount: 15400,
    reviewCount: 2900,
    isActive: true,
    isFeatured: false,
    isDealOfTheDay: true,
    approvalStatus: 'approved',
    warrantyInfo: '1 Year boAt Domestic Warranty',
    returnPolicy: '7 Days Replacement Policy',
    deliveryInfo: 'Guaranteed 1-Day Delivery in Metros',
    specifications: [
      { group: 'Audio', items: [{ name: 'Driver Size', value: '10mm Dynamic Drivers' }, { name: 'Active Noise Cancellation', value: 'Up to 32 dB' }] },
      { group: 'Battery', items: [{ name: 'Total Playback', value: 'Up to 42 Hours' }, { name: 'Charging Port', value: 'Type-C Fast Charge' }] }
    ],
    tags: ['boat', 'earbuds', 'anc', 'wireless', 'bluetooth', 'tws'],
    createdAt: '2026-01-14T00:00:00Z',
    updatedAt: '2026-01-14T00:00:00Z',
  },

  // 11. OnePlus 12 5G Smartphone
  {
    id: 'prod_op12',
    title: 'OnePlus 12 5G (Flowy Emerald, 16GB RAM, 512GB Storage)',
    slug: 'oneplus-12-5g-512gb',
    sku: '1PLUS-12-512-EMR',
    shortDescription: 'Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera, 2K 120 Hz ProXDR Display, 100W SUPERVOOC Charging.',
    description: 'The OnePlus 12 redefines the meaning of smooth. Seamlessly blending flagship hardware with state-of-the-art software optimizations, OnePlus 12 is Silky Smooth.',
    categoryId: 'cat_mobiles',
    categoryName: 'Mobiles & Tablets',
    categorySlug: 'mobiles',
    subcategoryId: 'sub_smartphones',
    subcategoryName: 'Smartphones',
    brandId: 'b_oneplus',
    brandName: 'OnePlus',
    sellerId: 'seller_apex_01',
    sellerStoreName: 'Apex Electronics & Lifestyle',
    mrp: 69999,
    price: 64999,
    discountPercent: 7,
    taxPercent: 18,
    stockQuantity: 30,
    thumbnailUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80',
    ],
    variants: [
      { id: 'var_op12_emr', productId: 'prod_op12', sku: '1PLUS-12-512-EMR', variantName: 'Flowy Emerald / 16GB / 512GB', color: 'Flowy Emerald', colorCode: '#1A4D3E', ram: '16GB', storage: '512GB', mrp: 69999, price: 64999, stockQuantity: 15 },
      { id: 'var_op12_blk', productId: 'prod_op12', sku: '1PLUS-12-512-BLK', variantName: 'Silky Black / 16GB / 512GB', color: 'Silky Black', colorCode: '#222222', ram: '16GB', storage: '512GB', mrp: 69999, price: 64999, stockQuantity: 15 },
    ],
    rating: 4.7,
    ratingCount: 3120,
    reviewCount: 680,
    isActive: true,
    isFeatured: true,
    isDealOfTheDay: false,
    approvalStatus: 'approved',
    warrantyInfo: '1 Year Brand Warranty',
    returnPolicy: '7 Days Replacement',
    deliveryInfo: 'Free Express Delivery',
    specifications: [
      { group: 'Key Features', items: [{ name: 'Processor', value: 'Qualcomm Snapdragon 8 Gen 3' }, { name: 'Main Camera', value: '50MP Sony LYT-808 with OIS + 64MP 3X Periscope + 48MP Ultra-Wide' }] }
    ],
    tags: ['oneplus', 'oneplus 12', 'flagship', '5g', 'hasselblad'],
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-01-15T00:00:00Z',
  },

  // 12. Organic Extra Virgin Olive Oil & Himalayan Pink Salt Combo
  {
    id: 'prod_organic_oil',
    title: 'NaturePure Cold-Pressed 100% Extra Virgin Olive Oil (1 Litre Glass Bottle)',
    slug: 'naturepure-extra-virgin-olive-oil-1l',
    sku: 'NP-EVOO-1000ML',
    shortDescription: 'First cold pressed from premium Mediterranean olives. High antioxidants and zero cholesterol.',
    description: 'NaturePure Extra Virgin Olive Oil is cold pressed within hours of olive harvest to preserve natural aromas, peppery finish, and heart-healthy polyphenols. Perfect for salads, sautéing, and gourmet cooking.',
    categoryId: 'cat_grocery',
    categoryName: 'Grocery & Essentials',
    categorySlug: 'grocery',
    subcategoryId: 'sub_staples',
    subcategoryName: 'Cooking Staples',
    brandName: 'NaturePure Organic',
    sellerId: 'seller_apex_01',
    sellerStoreName: 'Apex Electronics & Lifestyle',
    mrp: 1499,
    price: 999,
    discountPercent: 33,
    taxPercent: 5,
    stockQuantity: 100,
    thumbnailUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    ratingCount: 890,
    reviewCount: 140,
    isActive: true,
    isFeatured: false,
    isDealOfTheDay: false,
    approvalStatus: 'approved',
    warrantyInfo: 'FSSAI Certified 100% Pure Food Quality',
    returnPolicy: 'Non-returnable consumable item',
    deliveryInfo: 'Delivery in 24 Hours in select cities',
    specifications: [
      { group: 'Food Safety & Ingredients', items: [{ name: 'Ingredient Type', value: '100% Vegetarian' }, { name: 'Volume', value: '1000 ml' }, { name: 'Packaging', value: 'UV Protected Dark Glass Bottle' }] }
    ],
    tags: ['grocery', 'olive oil', 'cooking', 'organic', 'health'],
    createdAt: '2026-01-16T00:00:00Z',
    updatedAt: '2026-01-16T00:00:00Z',
  }
];

export const seedReviews: Review[] = [
  {
    id: 'rev_001',
    productId: 'prod_ip15promax',
    userId: 'usr_customer_001',
    userName: 'Rahul S.',
    rating: 5,
    title: 'Mindblowing performance and titanium finish!',
    comment: 'The natural titanium looks unreal in person. Battery life easily lasts 1.5 days on heavy usage and the 5x optical telephoto lens captures insane details. Super fast delivery by Prajnacart!',
    isVerifiedPurchase: true,
    helpfulVotes: 48,
    createdAt: '2026-01-20T14:30:00Z',
  },
  {
    id: 'rev_002',
    productId: 'prod_sony_xm5',
    userId: 'usr_customer_001',
    userName: 'Rahul S.',
    rating: 5,
    title: 'The best ANC headphones period.',
    comment: 'Soundstage is crisp with deep textured bass. The dual processor cancels out airplane cabin rumble and office chatter completely. 10/10 recommendation.',
    isVerifiedPurchase: true,
    helpfulVotes: 32,
    createdAt: '2026-01-22T09:15:00Z',
  }
];

export const seedOrders: Order[] = [
  {
    id: 'ord_demo_001',
    orderNumber: 'NM202608250001',
    userId: 'usr_customer_001',
    customerName: 'Rahul Sharma',
    customerEmail: 'customer@prajnacart.com',
    customerPhone: '9811122233',
    shippingAddress: seedAddresses[0],
    itemsSubtotal: 26990,
    discountAmount: 100,
    couponCode: 'WELCOME100',
    couponDiscount: 100,
    taxAmount: 0,
    shippingFee: 0,
    grandTotal: 26890,
    paymentMethod: 'razorpay',
    paymentStatus: 'paid',
    orderStatus: 'shipped',
    trackingId: 'TRK-DELHIVERY-98234120',
    placedAt: '2026-08-20T10:30:00Z',
    updatedAt: '2026-08-22T16:00:00Z',
    items: [
      {
        id: 'orditem_001',
        orderId: 'ord_demo_001',
        productId: 'prod_sony_xm5',
        sellerId: 'seller_prime_02',
        productTitle: 'Sony WH-1000XM5 Industry Leading Wireless Noise Cancelling Headphones',
        variantName: 'Midnight Black',
        thumbnailUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
        unitMrp: 34990,
        unitPrice: 26990,
        quantity: 1,
        totalPrice: 26990,
        itemStatus: 'shipped',
      }
    ],
    statusHistory: [
      { status: 'placed', timestamp: '2026-08-20T10:30:00Z', comment: 'Order placed successfully by customer' },
      { status: 'confirmed', timestamp: '2026-08-20T11:00:00Z', comment: 'Payment verified via Razorpay' },
      { status: 'processing', timestamp: '2026-08-21T09:00:00Z', comment: 'Order verified by seller PrimeTech SuperStore' },
      { status: 'packed', timestamp: '2026-08-21T17:30:00Z', comment: 'Package sealed with tamper-proof security tape' },
      { status: 'shipped', timestamp: '2026-08-22T16:00:00Z', comment: 'Handed over to courier hub. In transit to Bengaluru.' }
    ]
  }
];
